### ISSUE TITLE
where can I get data for models?

### ISSUE THREAD

**Issue by shgefu** [titu1994/LSTM-FCN#1]
where can I get data for models?

**Comment by titu1994** [comment]
The data can be obtained as a zip file from here -  http://www.cs.ucr.edu/~eamonn/time_series_data/

Extract that into some folder and it will give 85 different folders. Copy paste the util script `extract_all_datasets.py` and run it to get a single folder with all 85 dayasets extracted. 

Cut paste these files into the Data directory.

**Comment by shgefu** [comment]
Thank you very much!  I have got it and  run the model. 
When I use my finance stock data , it's accuracy is very low, maybe it's not strong for prediction.
do you have any suggestion for finance time serial data prediction?

**Comment by titu1994** [comment]
I don't know of any algorithm or model which does well for financial time series data like stocks etc. Even the best model would only get around random guess accuracy.
