### ISSUE TITLE
Attention on only one time step?

### ISSUE THREAD

**Issue by Microsheep** [titu1994/LSTM-FCN#11]
Since there will only be one time step, I am curious about what the attention mechanism will do.
According to my understanding, the attention process is to perform attention on the output of each timestamp, but since there is only one time step, it makes the difference between attention and normal LSTM strange.

Am I missing anything here? Thank you!

**Comment by titu1994** [comment]
Due to the use of dimension shuffling, attention is over 1 timesteps but over all features. Here, "features" are the timesteps themselves.

This is self attention on the features rather than temporal attention on timesteps.
