### ISSUE TITLE
Conv input permuted in code, but LSTM in paper?

### ISSUE THREAD

**Issue by komodovaran** [titu1994/LSTM-FCN#13]
In the paper you write

> the LSTM block (...) receives the input as a multivariate time series with a single time step. This is accomplished by the dimension shuffle layer, which transposes the temporal dimension of the time series.

But in the code you always permute the y-section, i.e. the convolutional part, and never the inputs for the LSTM:

```
def generate_model():
    ip = Input(shape=(MAX_NB_VARIABLES, MAX_TIMESTEPS))

    x = Masking()(ip)
    x = LSTM(8)(x)
    x = Dropout(0.8)(x)

    y = Permute((2, 1))(ip)
    y = Conv1D(...

    x = concatenate([x, y])

    out = Dense(NB_CLASS, activation='softmax')(x)
```

Did I misunderstand?

**Comment by titu1994** [comment]
The GitHub readme addresses this. The two ops are interchangeable. In either case, the lstm always receives the permuted input.
