### ISSUE TITLE
Time series data to be fed into CNN

### ISSUE THREAD

**Issue by zneha** [titu1994/LSTM-FCN#15]
Hello,
Can you direct me to exactly where you have converted or modified the time series data to be fed into a CNN?

**Comment by titu1994** [comment]
https://github.com/titu1994/LSTM-FCN/issues/3

The open issue here has directions to add new datasets. For lstm fcn which supports univariate datasets, you can simply add a csv file with each row being one time series. See the UCR datasets for examples of formats.
