### ISSUE TITLE
OSError: Unable to open file (Unable to open file: 

### ISSUE THREAD

**Issue by ligesangmeiduo** [titu1994/LSTM-FCN#2]
OSError: Unable to open file (Unable to open file: name = './weights/bird_chicke
n_weights.h5', errno = 2, error message = 'no such file or directory', flags = 0
, o_flags = 0)    Hello, in the weight folder, there is no% s_weights.h5 this file, so this error? New to deep learning, so I do not really understand

**Comment by titu1994** [comment]
Sorry, we are still preparing the weight files. They will be made available in a few weeks. 

For now, you could run the code in training mode to generate a weight file. If I recall, bird chicken was very fast to train.

**Comment by ligesangmeiduo** [comment]
Thank you for your answer! I read your code, but I do not know how to run the program in the training environment to generate the weight file. Can you guide me, be grateful!

**Comment by ligesangmeiduo** [comment]
Thanks for your answer! I read your code, but I do not know how to run the code in the training model to generate the weight file. Can you guide me, be grateful!

**Comment by titu1994** [comment]
@ligesangmeiduo After you download the datasets as mentioned in the `Installation` section of the readme.

Place the provided script `extract_all_datasets.py` stored in the `utils` directory in the same directory as the extracted datasets folders, and run it to generate a single folder `_data`. Cut all of the files out of this `data` folder and save it to the `data` directory in this repository to setup the data directory.

After that, open any of the dataset scripts you want and uncomment the `train_model(......)` line and run the script from the command line of from your IDE.

**Comment by ligesangmeiduo** [comment]
Thank you for your patience. I'm in trouble, I used to own the data to run the program, but errors are: ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (5000, 2048), but my data Form and UCR data form is the same. I used the bird_chicken_model.py program to run the data. My data form is a matrix of 5000 * 2049, the first column of the matrix is the label. Can you show me where the error is? I will be very grateful!

**Comment by fazlekarim** [comment]
There is something wrong with your dataset. The training set and testing set for Bird chicken should each be 20 by 512. Make sure you have the right dataset. Look at utils/constants to verify dimensions.

![image](https://user-images.githubusercontent.com/29384143/32236130-57fe9df8-be2f-11e7-86c3-49ba49cc3739.png)

**Comment by ligesangmeiduo** [comment]
However, the error displayed is the wrong dimension of the input data. Enter the required data dimension is three-dimensional, but I input data dimension is two-dimensional. In the form of training data and test data Bird chicken is a two-dimensional matrix, so I do not know why this error.

**Comment by titu1994** [comment]
Can you please show us a screenshot of the error, the dataset shape for train (both X and Y), and if possible, your `constants.py` file that you are editing?

**Comment by ligesangmeiduo** [comment]
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (5000, 2048)。I am very grateful to your patience, delay your valuable time I am also very sorry. Because my data is also a time series, so I would like to use your test. Training data 5000 samples, the time series length is 2048, for 10 categories. However, the above mistakes, I do not understand why.
constants.py：
TRAIN_FILES = [ '../data\\a_TRAIN.csv', # 0]

TEST_FILES = [ '../data\\a_TEST.csv',  # 0 ]

MAX_SEQUENCE_LENGTH_LIST = [2048, # 0  ]

NB_CLASSES_LIST = [10, #0 ]
Part of the data:
0 | -0.04381 | -0.06717 | -0.05382 | -0.04903 | -0.06071 | -0.06905 | -0.0484 | -0.00021 | 0.035465
0 | 0.04527 | -0.034 | -0.07594 | -0.04402 | 0.008971 | 0.046313 | 0.019818 | -0.00709 | 0.007719
0 | -0.01293 | 0.009179 | 0.004381 | 0.013769 | 0.062585 | 0.15458 | 0.20945 | 0.17857 | 0.097215
1 | 0.25305 | 0.25743 | 0.23845 | 0.21884 | 0.19172 | 0.14895 | 0.085115 | 0.009805 | -0.04903
1 | -0.07156 | -0.00605 | 0.067383 | 0.11766 | 0.12726 | 0.094086 | 0.03609 | -0.01231 | -0.04944
1 | 0.11203 | 0.087827 | 0.051528 | -0.00063 | -0.05487 | -0.09054 | -0.10034 | -0.08929 | -0.07135

**Comment by titu1994** [comment]
Sorry for the trouble, theres a check in the code to detect time series datasets which was buggy. For now, can you rename your files to remove the .csv part? They should be named just "a_TRAIN" and "a_TEST".

Another thing is, you should set MAX_SEQUENCE_LENGTH value to 2047, not 2048. The first column is the label, which will be extracted, leaving you with 2047 columns.

EDIT : I pushed a fix as well, so just pull the updated codebase and try running it. It should work with the above mentioned fixes.
