### ISSUE TITLE
fine tune

### ISSUE THREAD

**Issue by ligesangmeiduo** [titu1994/LSTM-FCN#5]
Hello, I saw a note in the code of LSTM-FCN that the fine-tuning model can be added, but the input data is one-dimensional. How to use a picture classification model like VGG16 for fine-tuning?

**Comment by titu1994** [comment]
The refinement algorithm from the paper is general. 

There are several blog posts and tutorials on how to fine-tune VGG models by freezing some layers and training only the fully connected layers etc, and that can extend that to the algorithm from the paper quite easily.
