### ISSUE TITLE
How to make a prediction

### ISSUE THREAD

**Issue by TinaZhangTing** [titu1994/LSTM-FCN#8]
hello, I have trained my own data, and how to make a prediction with a new unknown data(without labels)?
code like"result = pd.read_csv("unknown108.csv",header=None); model.predict(unknown)" doesnot work

**Comment by titu1994** [comment]
You can have a look at the evaluate script to see how the data is loaded and shaped in order to perform inference. Note that due to dimension shuffling, your data needs to be in the format (batch size, 1, Num of timesteps).
