### ISSUE TITLE
question about the input with one timestep to the LSTM layer

### ISSUE THREAD

**Issue by FelixHuiweiLin** [titu1994/LSTM-FCN#9]
Excuse me, sir. There is no doubt that the performance of your models is very good. But I have the same question as @zsh965866221 .

As we all know, LSTM is usually used to extract the features of time and the input shape of LSTM in Keras is that:

3D tensor with shape (batch_size, timesteps, input_dim).

However, you set the timestep as one in your paper and codes such as:

ip = Input(shape=(1, MAX_SEQUENCE_LENGTH))
x = LSTM(8)(ip)
x = Dropout(0.8)(x)
which means the shape of LSTM's input is (batch_size, 1 , MAX_SEQUENCE_LENGTH)

Emm, I just want to learn from you that whether it can extract the the features of time if it just has one timestep?

**Comment by titu1994** [comment]
Please refer to the comments on Issue https://github.com/titu1994/LSTM-FCN/issues/4
